In [7]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [8]:
df = sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [9]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X = df.drop('species', axis=1)
y = df['species']

In [13]:
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model_knn = KNeighborsClassifier()
model_knn.fit(train_X, train_y)
model_knn.score(test_X, test_y)

1.0

In [ ]:
from sklearn.svm import SVC
model_svc = SVC(gamma='auto')
model_svc.fit(train_X, train_y)
model_svc.score(test_X, test_y)

1.0

## Grid Search CV in action

In [24]:
from sklearn.model_selection import GridSearchCV

In [32]:
classifier = GridSearchCV((model_svc),{
    'C': [0.1, 1, 10, 20, 30, 100],
    'kernel': ['rbf','linear']
}, cv=5, return_train_score=False)

In [33]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(C=10, gamma='auto', kernel='linear'),
             param_grid={'C': [0.1, 1, 10, 20, 30, 100],
                         'kernel': ['rbf', 'linear']})

In [34]:
classifier.cv_results_

{'mean_fit_time': array([0.00240617, 0.00180893, 0.00261087, 0.0023232 , 0.00232897,
        0.00180798, 0.0020083 , 0.00180564, 0.00154037, 0.00201144,
        0.00221691, 0.0016129 ]),
 'std_fit_time': array([0.00049231, 0.00051271, 0.00097876, 0.00042009, 0.00039152,
        0.00051544, 0.00031693, 0.00051135, 0.00041085, 0.00063018,
        0.00083136, 0.00037405]),
 'mean_score_time': array([0.00160761, 0.00140748, 0.00211253, 0.00201082, 0.00242186,
        0.00150676, 0.00110302, 0.00140562, 0.00150652, 0.0014029 ,
        0.0012063 , 0.0016243 ]),
 'std_score_time': array([0.00037024, 0.00049878, 0.00074086, 0.00032175, 0.00038507,
        0.00063627, 0.00066656, 0.00058659, 0.00045237, 0.00037628,
        0.00025224, 0.00060187]),
 'param_C': masked_array(data=[0.1, 0.1, 1.0, 1.0, 10.0, 10.0, 20.0, 20.0, 30.0, 30.0,
                    100.0, 100.0],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=1e+20),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 0.1, 'kernel': 'rbf'},
  {'C': 0.1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'},
  {'C': 100, 'kernel': 'rbf'},
  {'C': 100, 'kernel': 'linear'}],
 'split0_test_score': array([0.9       , 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        1.        , 0.96666667, 1.        , 0.96666667, 1.        ,
        1.        , 1.        ]),
 'split1_test_score': array([0.96666667, 0.96666667, 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        0.96666667, 1.        ]),
 'split2_test_score': array([0.93333333, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.9       , 0.9       , 0.9       , 0.9       , 0.9       ,
        0.9       , 0.9       ]),
 'split3_test_score': array([0.93333333, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.93333333, 0.93333333, 0.9       ,
        0.93333333, 0.93333333]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.94666667, 0.97333333, 0.98      , 0.98      , 0.98      ,
        0.97333333, 0.96666667, 0.96666667, 0.96      , 0.96      ,
        0.96      , 0.96666667]),
 'std_test_score': array([0.03399346, 0.01333333, 0.01632993, 0.01632993, 0.01632993,
        0.03887301, 0.03651484, 0.0421637 , 0.03887301, 0.04898979,
        0.03887301, 0.0421637 ]),
 'rank_test_score': array([12,  4,  1,  1,  1,  4,  6,  7,  9,  9,  9,  7])}

In [35]:
results = pd.DataFrame(classifier.cv_results_)
results.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002406,0.000492,0.001608,0.000370,0.1,rbf,"{'C': 0.1, 'kernel': 'rbf'}",0.900000,0.966667,0.933333,0.933333,1.0,0.946667,0.033993,12
1,0.001809,0.000513,0.001407,0.000499,0.1,linear,"{'C': 0.1, 'kernel': 'linear'}",0.966667,0.966667,0.966667,0.966667,1.0,0.973333,0.013333,4
2,0.002611,0.000979,0.002113,0.000741,1.0,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.002323,0.000420,0.002011,0.000322,1.0,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
4,0.002329,0.000392,0.002422,0.000385,10.0,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1

In [36]:
results[['param_C', 'param_kernel', 'mean_test_score']]

    param_C param_kernel  mean_test_score
0       0.1          rbf         0.946667
1       0.1       linear         0.973333
2       1.0          rbf         0.980000
3       1.0       linear         0.980000
4      10.0          rbf         0.980000
5      10.0       linear         0.973333
6      20.0          rbf         0.966667
7      20.0       linear         0.966667
8      30.0          rbf         0.960000
9      30.0       linear         0.960000
10    100.0          rbf         0.960000
11    100.0       linear         0.966667

In [37]:
classifier2 = GridSearchCV((model_knn),{
    'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'weights': ['uniform', 'distance']
}, cv=5, return_train_score=False)

In [38]:
classifier2.fit(X, y)
classifier2.cv_results_
results2 = pd.DataFrame(classifier2.cv_results_)
results2.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002022,0.000032,0.004818,0.001362,1,uniform,"{'n_neighbors': 1, 'weights': 'uniform'}",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,17
1,0.001718,0.000888,0.002006,0.000955,1,distance,"{'n_neighbors': 1, 'weights': 'distance'}",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,17
2,0.002622,0.001025,0.003934,0.000503,2,uniform,"{'n_neighbors': 2, 'weights': 'uniform'}",0.966667,0.933333,0.933333,0.900000,1.0,0.946667,0.033993,20
3,0.002926,0.000587,0.003237,0.000789,2,distance,"{'n_neighbors': 2, 'weights': 'distance'}",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,17
4,0.001917,0.000745,0.004835,0.001411,3,uniform,"{'n_neighbors': 3, 'weights': 'uniform'}",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,12

In [39]:
results2[['param_n_neighbors', 'param_weights', 'mean_test_score']]

    param_n_neighbors param_weights  mean_test_score
0                   1       uniform         0.960000
1                   1      distance         0.960000
2                   2       uniform         0.946667
3                   2      distance         0.960000
4                   3       uniform         0.966667
5                   3      distance         0.966667
6                   4       uniform         0.973333
7                   4      distance         0.966667
8                   5       uniform         0.973333
9                   5      distance         0.966667
10                  6       uniform         0.980000
11                  6      distance         0.980000
12                  7       uniform         0.980000
13                  7      distance         0.980000
14                  8       uniform         0.966667
15                  8      distance         0.980000
16                  9       uniform         0.973333
17                  9      distance         0.973333
18                 10       uniform         0.980000
19                 10      distance         0.986667